### ISSUE TITLE
LASR Dev Build 0.2 (game dosent appear to randomize like the previous version)

### ISSUE THREAD

**Issue by isrever** [Owen-Splat/LAS-Randomizer#1]
When using 0.1 the title screen would shows "The legend of zelda link's awakening RANDOMIZER" which i have been using to check if the game loaded the randomzied files.

As of Build 2.03 The title screen only shows "The legend of zelda link's awakening" which makes it hard to know whether the game is randomzied. and when loaded none of the items were randomized. 
![image](https://user-images.githubusercontent.com/20737861/208723294-201bc6b0-f1a0-4f26-8d66-a745991cf9d7.png)
![image](https://user-images.githubusercontent.com/20737861/208723583-74502fd8-b6dd-4168-ba6d-8fdd342e8ccb.png)

**Comment by Owen-Splat** [comment]
Hello, sorry for the late response! New version .0205 is out. It fixes a
ton of bugs, however the generation did work fine on 0.203. I suspect
the issue here is because there's now an extra folder in the output
containing the game's title ID. Example: ArrogantBusyFox/TitleID/Romfs/...
